model:
  model_config_params:
    model_name: sd_base
    model_id: "stabilityai/stable-diffusion-2-1"
    low_mem_mode: True
    compile_model: True
    lora_weights: null

  model_forward_params: 
    strength: 0.2
    num_steps: 20