project_name: ImagineDriving

datasets:
  train_data:
    dataset: pandaset
    path: "data/pandaset"
    data_getters:
      rgb:
        camera: "front_left_camera"

      prompt: 
        type: static
        positive_prompt: ""
        negative_prompt: ""

      meta: {}

    data_tree: 
      pandaset: 
        #001-124: "0::1"
        #001: "0::8"
        001:
          - 01
          

  val_data: 
    dataset: pandaset
    path: "data/pandaset"
    data_getters:
      rgb:
        camera: "front_left_camera"

      prompt: 
        type: static
        positive_prompt: ""
        negative_prompt: ""

      meta: {}

    data_tree: 
      pandaset: 
        #139-158: "0::16"
        #101: "0::16"
        001:
         - 01
        # - 09

model_type: sd
model_id: stabilityai/stable-diffusion-2-1

seed: 0
train_batch_size: 16
dataloader_num_workers: 0

max_grad_norm: 1.0

n_epochs: 1000
val_freq: 1
checkpointing_steps: 5

train_noise_strength: 0.1
train_noise_num_steps: null

val_noise_num_steps: 50
val_noise_strength: 0.1

learning_rate: 0.0003
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 0.00000001

lr_scheduler: "constant"
lr_warmup_steps: 1000

#lr_scheduler: "cosine_with_restarts"
#lr_warmup_steps: 1000
#lr_scheduler_kwargs:
#  num_cycles: 2

center_crop: True
flip_prob: 0

#center_crop: False
#flip_prob: 0.5

use_debug_loss: False
use_recreation_loss: Trues

use_controlnet: False

control_lora_rank_linear: 4
control_lora_rank_conv2d: 4
lora_target_ranks: 
  unet: 
    downblocks: 
      attn: 8
      resnet: 8
      ff: 8
      proj: 8
      
    midblocks:
      attn: 8
      resnet: 8
      ff: 8
      proj: 8
    upblocks:
      attn: 8
      resnet: 8
      ff: 8
      proj: 8

trainable_models:
  - unet

logging_dir: logs/finetune/sd
output_dir: output/finetune/sd

loggers: ["wandb"]
#loggers: []
